In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# Lab 7 ‚Äì Regular Expressions

## DSC 80, Spring 2022

### Due Date: Monday, May 16th at 11:59 PM

## Instructions
Much like in DSC 10, this Jupyter Notebook contains the statements of the problems and provides code and Markdown cells to display your answers to the problems. Unlike DSC 10, the notebook is *only* for displaying a readable version of your final answers. The coding will be done in an accompanying `lab.py` file that is imported into the current notebook.

Labs and programming assignments will be graded in (at most) two ways:
1. The functions and classes in the accompanying `lab.py` file will be tested (a la DSC 20),
2. The notebook may be graded (if it contains free response questions or asks you to draw plots).

**Do not change the function names in the `lab.py` file!**
- The functions in the `lab.py` file are how your assignment is graded, and they are graded by their name.
- If you changed something you weren't supposed to, just use git to revert! Ask us if you need help with this, or google around for `git revert`.

**Tips for working in the notebook**:
- The notebooks serve to present the questions and give you a place to present your results for later review.
- The notebooks in *lab assignments* are not graded (only the `lab.py` file is submitted and graded).
- The notebook serves as a nice environment for 'pre-development' and experimentation before designing your function in your `lab.py` file. You can write code here, but make sure that all of your real work is in the `lab.py` file.

**Tips for developing in the `lab.py` file**:
- Do not change the function names in the starter code; grading is done using these function names.
- Do not change the docstrings in the functions. These are there to tell you if your work is on the right track!
- You are encouraged to write your own additional helper functions to solve the lab! 
- Always document your code!

### Importing code from `lab.py`

* We import our `lab.py` file that's contained in the same directory as this notebook.
* We use the `autoreload` notebook extension to make changes to our `lab.py` file immediately available in our notebook. Without this extension, we would need to restart the notebook kernel to see any changes to `lab.py` in the notebook.
    - `autoreload` is necessary because, upon import, `lab.py` is compiled to bytecode (in the directory `__pycache__`). Subsequent imports of `lab` merely import the existing compiled python.

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from lab import *

In [5]:
import pandas as pd
import numpy as np
import os
import re

***Note:*** While working on the lab, check the Campuswire post titled "Lab 7 Released!" for any clarifications.

## Question 1 ‚Äì Practice with Regular Expressions üõ†

Regular expressions can be tricky, and the best way to gain familiarity with them is through lots of practice. In this question, you will work through ten exercises, each of which requires you to write a regular expression that matches strings that satisfy certain criteria. Make sure to take a close look at the doctests for each function in `lab.py`, as they provide useful guidance for the types of strings you should and shouldn't match.

***Notes:*** 
- Make sure to refer to the [Regular Expression Resources](https://dsc80.com/resources/) posted on the course website. In particular, we recommend having [regex101.com](https://regex101.com/) open while working, along with the [cheat sheet](https://dsc80.com/resources/other/berkeley-regex-reference.pdf).

- Each exercise has a star rating, between 1 (‚≠êÔ∏è) and 3 (‚≠êÔ∏è‚≠êÔ∏è‚≠êÔ∏è) stars, indicating its difficulty level (1 being the easiest, 3 being the hardest). If you are spending lots of time on 1-star exercises, take a close look at the syntax from lecture, as there is probably an easier way of writing the necessary pattern!

<br>

### Exercise 1 (‚≠êÔ∏è)

Write a regular expression that matches strings that have `'['` as the third character and `']'` as the sixth character.

<br>

### Exercise 2 (‚≠êÔ∏è)

Write a regular expression that matches strings that are phone numbers that start with `'(858)'` and follow the format `'(xxx) xxx-xxxx'` (`'x'` represents a digit).

***Note:*** There is a space between `'(xxx)'` and `'xxx-xxxx'`.

<br>

### Exercise 3 (‚≠êÔ∏è)

Write a regular expression that matches strings that:
- are between 6 and 10 characters long (inclusive),
- contain only alphanumeric characters, whitespace and `'?'`, and
- end with `'?'`.

<br>

### Exercise 4 (‚≠êÔ∏è‚≠êÔ∏è)

Write a regular expression that matches strings with exactly two `'$'`, one of which is at the start of the string, such that:
- the characters between the two `'$'` can be anything (including nothing) except the lowercase letters `'a'`, `'b'`, and `'c'`, (and `'$'`), and
- the characters after the second `'$'` can only be the **lowercase or uppercase** letters `'a'`/`'A'`, `'b'`/`'B'`, and `'c'`/`'C'`, with every `'a'`/`'A'` before every `'b'`/`'B'`, and every `'b'`/`'B'` before every `'c'`/`'C'`. There must be at least one `'a'` or `'A'`, at least one `'b'` or `'B'`, and at least one `'c'` or `'C'`.
    

<br>

### Exercise 5 (‚≠êÔ∏è)
Write a regular expression that matches strings that represent valid Python file names, including the extension. 

***Note:*** For simplicity, assume that file names contains only letters, numbers, and underscores (`'_'`).

<br>

### Exercise 6 (‚≠êÔ∏è)
Write a regular expression that matches strings that:
- are made up of only lowercase letters and exactly one underscore (`'_'`), and
- have at least one lowercase letter on both sides of the underscore.

<br>

### Exercise 7 (‚≠êÔ∏è)
Write a regular expression that matches strings that start with and end with an underscore (`'_'`).

<br>

### Exercise 8 (‚≠êÔ∏è)

Apple serial numbers are strings of length 1 or more that are made up of any characters, other than
- the uppercase letter `'O'`, 
- the lowercase letter `'i`', and 
- the number `'1'`.

Write a regular expression that matches strings that are valid Apple serial numbers.

<br>

### Exercise 9 (‚≠êÔ∏è‚≠êÔ∏è)

ID numbers are formatted as `'SC-NN-CCC-NNNN'`, where 
- SC represents state code in uppercase (e.g. `'CA'`),
- NN represents a number with 2 digits (e.g. `'98'`),
- CCC represents a three letter city code in uppercase (e.g. `'SAN'`), and
- NNNN represents a number with 4 digits (e.g. `'1024'`).

Write a regular expression that matches strings that are ID numbers corresponding to the cities of `'SAN'` or `'LAX'`, or the state of `'NY'`. Assume that there is only one city named `'SAN'` and only one city named `'LAX'`.

<br>

### Exercise 10 (‚≠êÔ∏è‚≠êÔ∏è‚≠êÔ∏è)

Write a function named `match_10` that takes in a string and:
- converts the string to lowercase,
- removes all non-alphanumeric characters (i.e. removes everything that is not in the `\w` character class), and the letter `'a'`, and
- returns a list of every **non-overlapping** three-character substring in the remaining string, starting from the beginning of the string.
   
For instance, consider the following doctest:

```py
>>> match_10('Ab..DEF')
['bde']
```

Here's how `match_10` should process `'Ab..DEF'`:

1. Convert to lowercase: `'ab..def'`.
2. Remove non-alphanumeric characters and the letter `'a'`: `'bdef'`.
3. Starting from the beginning of the string, there is only a single non-overlapping three character substring: `'bde'`. Hence, we return `['bde']`.

***Note:*** Perform your operations in the exact order described above, otherwise your code may not pass all the tests.

In [22]:
string = 'Ab..DEFbt'
filter2 = string.lower()
filter2 = filter2.replace('a','')
filter2 = re.findall('[\w]',filter2)
filter2 = ''.join(filter2)
#filter2

re.findall('\w{3}',filter2)

['bde', 'fbt']

In [23]:
grader.check("q1")

q1 results: All test cases passed!

## Question 2 ‚Äì Capturing Groups in Regular Expressions üì°

The dataset stored in `data/messy.txt` contains personal information from a fictional website that a user scraped from web server logs. Within this dataset, there are four fields that are of interest to you:
1. Email Addresses (assume they are alphanumeric usernames and domain names)
2. [Social Security Numbers](https://en.wikipedia.org/wiki/Social_Security_number#Structure)
3. Bitcoin Addresses (alphanumeric strings of long length)
4. Street Addresses

Create a function `extract_personal` that takes in a string containing the contents of a server log file (like `open('data/messy.txt').read()`) and returns a **tuple of four separate lists** containing values of the 4 pieces of information listed above (in the order listed above). Do **not** keep empty values.

***Note:*** Since this data is messy, your function will be allowed to miss ~5% of the records in each list. Good spot checking using certain useful substrings (e.g. `'@'` for emails) should help assure correctness! Your function will be tested on a sample of the file `messy.txt`.

***Hint:*** There are multiple "delimiters" in use in the file; there are few enough of them that you can safely determine what they are.

In [45]:
# experiment with extract_personal using the file s below
fp = os.path.join('data', 'messy.txt')
s = open(fp, encoding='utf8').read()

In [52]:
emails = re.findall('(\w+@[\w]+\.[\w]+(?:\.[\w]+)*)',s)

In [76]:
len(emails)

938

In [56]:
ssn = re.findall('ssn:(\d{3}-\d{2}-\d{4})',s)

In [57]:
ssn

['380-09-9403',
 '118-12-8276',
 '427-22-9352',
 '649-16-2247',
 '265-90-3805',
 '552-37-4756',
 '757-41-7191',
 '855-12-9209',
 '592-06-3498',
 '295-47-4318',
 '487-70-8307',
 '388-94-8970',
 '672-36-5180',
 '493-79-8907',
 '797-87-2569',
 '634-49-4764',
 '236-77-4126',
 '419-91-7185',
 '608-41-6360',
 '850-99-8257',
 '634-32-0336',
 '466-29-7843',
 '219-94-1536',
 '606-83-6633',
 '225-28-2622',
 '158-80-4556',
 '579-70-9026',
 '561-14-1915',
 '619-94-3154',
 '554-21-4300',
 '494-98-3760',
 '535-06-0965',
 '435-17-2290',
 '493-31-9068',
 '898-20-5714',
 '645-60-2112',
 '521-33-6224',
 '177-64-8758',
 '705-22-5915',
 '626-83-3638',
 '296-71-6465',
 '623-74-3100',
 '462-34-3229',
 '672-84-3797',
 '551-76-0257',
 '612-43-4860',
 '540-35-6767',
 '882-68-5364',
 '361-38-8584',
 '497-99-1297',
 '308-27-2080',
 '774-78-1689',
 '159-44-5881',
 '763-29-1574',
 '186-51-3531',
 '110-65-7380',
 '728-96-0460',
 '235-88-1295',
 '270-62-8459',
 '247-78-4274',
 '447-90-1874',
 '685-64-3362',
 '431-58-6482',
 '876-49-2071',
 '381-39-0527',
 '597-45-0737',
 '875-09-1162',
 '213-69-2551',
 '651-47-2895',
 '172-09-5766',
 '452-88-2700',
 '148-88-8265',
 '415-53-5504',
 '406-16-8030',
 '756-04-0165',
 '646-92-5656',
 '140-48-1762',
 '711-45-1734',
 '854-29-8926',
 '336-11-2087',
 '519-99-3355',
 '829-51-1182',
 '893-48-7577',
 '695-62-6576',
 '736-45-4957',
 '873-41-4004',
 '338-78-5741',
 '259-84-4947',
 '181-58-4928',
 '332-14-2769',
 '397-79-0235',
 '236-80-7426',
 '636-93-2695',
 '119-18-9412',
 '706-19-6522',
 '812-10-4887',
 '740-70-4227',
 '804-52-0763',
 '797-56-2842',
 '255-01-3731',
 '413-52-3112',
 '683-69-2305',
 '283-78-5904',
 '526-84-6712',
 '678-55-9829',
 '803-24-0761',
 '123-28-0146',
 '604-62-8504',
 '885-75-3028',
 '789-44-3014',
 '732-61-7821',
 '768-08-2857',
 '198-30-1204',
 '253-09-7398',
 '891-94-5586',
 '173-95-5477',
 '452-72-2064',
 '463-11-2286',
 '282-95-8489',
 '266-26-6612',
 '513-96-0163',
 '156-46-6302',
 '345-77-4891',
 '716-95-9483',
 '762-36-4786',
 '468-17-8762',
 '429-84-1678',
 '675-92-0315',
 '567-70-6695',
 '799-10-1947',
 '267-24-4232',
 '482-26-9255',
 '653-43-4404',
 '421-99-3229',
 '329-48-8247',
 '814-44-0588',
 '431-87-2656',
 '822-55-8279',
 '386-15-0407',
 '204-04-7233',
 '424-37-1143',
 '643-47-5461',
 '487-13-2807',
 '139-01-1981',
 '746-92-4822',
 '230-03-6223',
 '462-95-7742',
 '535-01-4606',
 '108-17-9923',
 '283-53-2060',
 '736-24-7547',
 '864-74-3606',
 '618-19-9226',
 '407-71-8795',
 '145-42-0546',
 '117-68-4460',
 '379-68-2749',
 '859-11-1280',
 '544-85-6909',
 '227-94-4526',
 '414-03-0347',
 '690-72-0527',
 '407-63-8633',
 '535-42-9905',
 '760-88-9871',
 '612-85-5962',
 '897-82-7950',
 '439-83-3493',
 '278-10-3887',
 '102-56-6515',
 '849-36-9397',
 '723-18-9479',
 '468-80-4924',
 '485-47-9526',
 '622-76-6437',
 '219-86-7630',
 '835-47-1056',
 '691-83-7764',
 '463-27-5874',
 '638-95-2671',
 '702-10-3712',
 '803-01-9689',
 '345-95-7433',
 '250-40-1683',
 '291-75-8331',
 '632-22-4582',
 '487-51-2954',
 '420-84-0652',
 '602-71-8130',
 '437-24-7365',
 '844-91-3484',
 '403-46-8238',
 '529-56-0450',
 '830-73-3174',
 '252-36-6654',
 '653-57-6008',
 '411-51-8344',
 '121-70-7751',
 '755-21-1732',
 '131-12-8857',
 '610-68-6840',
 '323-10-1168',
 '523-71-8530',
 '218-12-5344',
 '118-90-0848',
 '503-70-7211',
 '369-57-6064',
 '138-97-7568',
 '103-48-0676',
 '511-60-8887',
 '422-64-8159',
 '385-34-7309',
 '259-24-1442',
 '576-86-4526',
 '694-56-1333',
 '124-52-6364',
 '700-71-9041',
 '713-15-8301',
 '224-83-6439',
 '471-83-2280',
 '566-09-4019',
 '162-07-8312',
 '527-75-0396',
 '364-47-6224',
 '539-67-6002',
 '676-18-8405',
 '472-59-1962',
 '457-61-2083',
 '416-87-5290',
 '667-22-8971',
 '641-69-6074',
 '568-77-1338',
 '127-81-8691',
 '225-09-6724',
 '447-98-7531',
 '773-19-6837',
 '716-67-0819',
 '846-84-1808',
 '319-83-2629',
 '579-10-2003',
 '531-38-3328',
 '303-26-7998',
 '100-39-4709',
 '794-09-6867',
 '331-79-9705',
 '513-42-1965',
 '729-39-9134',
 '225-72-1202',
 '853-85-6963',
 '544-48-2844',
 '206-03-3803',
 '866-96-3153',
 '863-72-2617',
 '792-27-9294',
 '732-04-3964',
 '810-45-9448',
 '655-75-9111',
 '321-06-3982',
 '287-94-8606',
 '233-02-5615',
 '464-49-3765',
 '878-47-7548',
 '444-90-4827',
 '855-17-5441',
 '691-36-6043',
 '182-16-9326',
 '235-87-9873',
 '295-02-3985',
 '602-25-8065',
 '403-60-8879',
 '182-25-1773',
 '755-93-5324',
 '638-74-3116',
 '210-54-5616',
 '385-79-5962',
 '812-05-8983',
 '347-25-3949',
 '200-16-7663',
 '517-02-6928',
 '298-38-7813',
 '648-72-4686',
 '623-19-7560',
 '804-18-5636',
 '374-94-7327',
 '255-07-7211',
 '356-30-1710',
 '475-47-1833',
 '498-16-8446',
 '809-43-8342',
 '327-05-1149',
 '333-05-7038',
 '458-19-8750',
 '421-03-8150',
 '183-01-8884',
 '188-91-0680',
 '683-69-4466',
 '453-24-3921',
 '757-55-8653',
 '281-58-8587',
 '830-79-0445',
 '169-47-3775',
 '483-88-8760',
 '575-26-9504',
 '284-35-2725',
 '502-59-8466',
 '320-90-1573',
 '433-30-4849',
 '208-51-5307',
 '237-57-0044',
 '890-18-1805',
 '617-29-9687',
 '747-69-9697',
 '895-23-0277',
 '596-81-7248',
 '878-62-8015',
 '266-20-1087',
 '774-30-0740',
 '139-58-6720',
 '407-91-2088',
 '866-80-2748',
 '894-04-9054',
 '211-45-1653',
 '418-35-6045',
 '424-56-1664',
 '340-52-8411',
 '599-67-3712',
 '874-47-0471',
 '111-70-3092',
 '588-28-1354',
 '247-22-5636',
 '325-63-1596',
 '442-14-0469',
 '788-32-2664',
 '153-24-1709',
 '248-47-1557',
 '877-44-1521',
 '826-73-1099',
 '619-45-0316',
 '537-35-6407',
 '405-93-8455',
 '232-07-4254',
 '263-87-1661',
 '631-31-8168',
 '865-54-0154',
 '519-03-5224',
 '343-89-4806',
 '198-82-6446',
 '803-41-6906',
 '700-14-6543',
 '814-01-0863',
 '683-97-1983',
 '400-51-7561',
 '177-81-5745',
 '318-01-6368',
 '413-44-8627',
 '507-69-4425',
 '328-86-2305',
 '115-12-9353',
 '454-67-7109',
 '536-18-7818',
 '158-84-1546',
 '873-36-1984',
 '434-51-9987',
 '330-81-4794',
 '212-65-7796',
 '246-89-1891',
 '641-32-2497',
 '835-70-3137',
 '817-63-2535',
 '870-16-4804',
 '183-52-2696',
 '572-48-4605',
 '797-37-6300',
 '154-92-0944',
 '744-62-2548',
 '777-57-0223',
 '190-83-7892',
 '631-59-6196',
 '155-27-5863',
 '111-66-1914',
 '515-95-6196',
 '436-61-8200',
 '771-16-2841',
 '741-31-7481',
 '154-44-3014',
 '276-82-7908',
 '287-96-4824',
 '188-68-6103',
 '740-05-7177',
 '254-69-1255',
 '607-35-1635',
 '380-04-8834',
 '156-52-9474',
 '464-62-9563',
 '282-79-2884',
 '709-81-2246',
 '478-18-2537',
 '368-39-6549',
 '454-28-6980',
 '868-09-7237',
 '652-27-0391',
 '613-96-9555',
 '259-95-5806',
 '872-43-7631',
 '831-32-0083',
 '452-80-5673',
 '195-41-0743',
 '459-49-9278',
 '650-72-3030',
 '835-59-2512',
 '869-18-9971',
 '352-59-6251',
 '200-94-9569',
 '146-87-5194',
 '182-81-1381',
 '406-62-0854',
 '617-99-0774',
 '411-49-0984',
 '494-92-8050',
 '812-62-5298',
 '564-71-5699',
 '271-38-9915',
 '717-73-2740',
 '245-11-9938',
 '612-70-7685',
 '543-94-3451',
 '576-57-1881',
 '816-42-5391',
 '776-52-2115',
 '884-82-5622',
 '882-27-8055',
 '660-69-7575',
 '639-54-9911',
 '320-72-5388',
 '561-13-8508',
 '284-66-6949',
 '263-89-6791',
 '364-16-9584',
 '296-15-7844',
 '694-55-9099',
 '891-75-1259',
 '724-98-4650',
 '750-36-7399',
 '439-03-3099',
 '801-76-2142',
 '135-33-7399',
 '549-19-7531',
 '802-52-6489',
 '479-81-4431',
 '171-88-3572',
 '465-35-7402',
 '508-50-7920',
 '560-77-8523',
 '634-16-3145',
 '684-29-9448',
 '509-13-1520',
 '567-28-7335',
 '588-13-7990',
 '541-32-8656',
 '835-74-3981',
 '146-56-1241',
 '849-26-2269',
 '818-07-5480',
 '803-28-2143',
 '600-19-6171',
 '652-82-9928',
 '430-30-0689',
 '828-61-3520',
 '357-69-2659',
 '562-51-6806',
 '576-61-1157',
 '543-29-1037',
 '209-39-5983',
 '616-16-3354',
 '756-50-9498',
 '507-40-3868',
 '626-74-3027',
 '336-01-3309',
 '831-64-5952',
 '895-59-1377',
 '796-70-0407',
 '244-18-6469',
 '686-34-9380',
 '862-83-3640',
 '102-29-0830',
 '846-59-0715',
 '816-82-3005',
 '354-69-7872',
 '814-75-4575',
 '741-17-4356',
 '627-77-3930',
 '834-45-5528',
 '857-60-3341',
 '588-81-2643',
 '805-64-4089',
 '613-77-9764',
 '792-27-8116',
 '238-61-4410',
 '488-26-0848',
 '498-27-8866',
 '625-50-7733',
 '410-23-3640',
 '494-95-6354',
 '591-01-1374',
 '637-26-0942',
 '211-27-0947',
 '576-19-1149',
 '790-15-3773',
 '559-79-1186',
 '225-01-8743',
 '221-93-0735',
 '699-40-1064',
 '827-80-2563',
 '291-61-3978',
 '480-23-0101',
 '793-64-4468',
 '201-30-6899',
 '575-49-1575',
 '842-49-4436',
 '604-65-2003',
 '807-37-3040',
 '273-79-7463',
 '609-77-6891',
 '442-64-0868',
 '313-49-1992',
 '610-55-3749',
 '240-83-0285',
 '642-25-7931',
 '895-88-1188',
 '783-03-9876',
 '855-81-2881',
 '623-12-6772',
 '124-46-2147',
 '311-95-0001',
 '809-51-4285',
 '197-79-8651',
 '725-09-2451',
 '468-55-9354',
 '682-04-5154',
 '228-64-3693',
 '814-16-7110',
 '278-25-0332',
 '762-85-2155',
 '121-96-5361',
 '621-79-2447',
 '160-87-5230',
 '442-16-3752',
 '706-39-2200',
 '385-94-9028',
 '508-85-1397',
 '738-77-8989',
 '540-36-5534',
 '570-06-6253',
 '614-34-6922',
 '510-28-7403',
 '444-98-6908',
 '174-73-6048',
 '330-18-0097',
 '882-82-5494',
 '110-74-5178',
 '792-61-2101',
 '249-04-7380',
 '371-79-5470',
 '596-95-2193',
 '545-66-0045',
 '883-63-2335',
 '502-98-1034',
 '654-44-4450',
 '840-13-0090',
 '399-75-9140',
 '592-10-3400',
 '608-73-6297',
 '276-20-9165',
 '864-68-1837',
 '390-88-9754',
 '520-74-0885',
 '686-82-4588',
 '270-59-1860',
 '480-59-9172',
 '627-34-3582',
 '207-08-5326',
 '892-85-9029',
 '191-38-2383',
 '386-10-9700',
 '229-75-3659',
 '629-59-3989',
 '515-88-7072',
 '893-90-4182',
 '879-58-0126',
 '620-70-7341',
 '478-89-5604',
 '690-79-6020',
 '344-48-8573',
 '735-51-3694',
 '758-58-2946',
 '553-72-7574',
 '831-83-8215',
 '759-05-6440',
 '413-67-7535',
 '121-39-6058',
 '311-20-3797',
 '562-84-5509',
 '576-99-4360',
 '256-85-4282',
 '691-71-4065',
 '416-97-9597',
 '823-47-3989',
 '271-64-8684',
 '115-60-9363',
 '866-22-9101',
 '544-03-3133',
 '495-27-2338',
 '550-40-0191',
 '678-34-1239',
 '811-83-9568',
 '252-23-1634',
 '231-94-2100',
 '799-57-6629',
 '570-70-7295',
 '489-36-9035',
 '460-31-8488',
 '224-52-6034',
 '215-66-2537',
 '230-70-7344',
 '763-94-0621',
 '160-51-9460',
 '525-06-1238',
 '628-35-4550',
 '379-38-4791',
 '661-60-4335',
 '758-44-5469',
 '319-16-2432',
 '456-43-4674',
 '740-94-1836',
 '486-23-8022',
 '708-24-8468',
 '444-42-6862',
 '789-07-3616',
 '575-66-7711',
 '795-43-2821',
 '838-20-4946',
 '782-47-0463',
 '286-57-4159',
 '527-37-7913',
 '236-48-6330',
 '481-92-5848',
 '739-98-0070',
 '775-14-0053',
 '273-52-0124',
 '604-28-9617',
 '317-75-2701',
 '496-98-0167',
 '864-67-3719',
 '761-17-9237',
 '230-85-8652',
 '145-58-5463',
 '300-54-5896',
 '251-51-4015',
 '759-55-5005',
 '776-94-2132',
 '396-57-6251',
 '783-86-6555',
 '770-90-1375',
 '667-06-0541',
 '709-10-1717',
 '162-48-4582',
 '178-55-3038',
 '610-25-0811',
 '370-09-8973',
 '771-66-2830',
 '662-30-8154',
 '320-19-4112',
 '251-43-4967',
 '853-71-9790',
 '285-53-7504',
 '819-64-8550',
 '883-62-8177',
 '345-54-6557',
 '125-95-1374',
 '854-55-4143',
 '650-33-0749',
 '329-65-5189',
 '561-46-0918',
 '613-13-1700',
 '281-82-0280',
 '768-54-9818',
 '234-88-4130',
 '559-55-9074',
 '205-44-8015',
 '267-82-3802',
 '233-66-1927',
 '330-48-4186',
 '448-03-3624',
 '205-92-7107',
 '136-83-9177',
 '511-76-9875',
 '360-45-9771',
 '759-03-4263',
 '400-26-1210',
 '676-66-2244',
 '871-75-0784',
 '176-84-4522',
 '168-78-6741',
 '446-54-0204',
 '816-85-7763',
 '554-07-4081',
 '181-55-7418',
 '750-96-7810',
 '767-39-9733',
 '876-31-5739',
 '469-76-7617',
 '158-72-4893',
 '311-87-6159',
 '678-38-2460',
 '838-13-2827',
 '481-17-0641',
 '857-37-4210',
 '848-78-4002',
 '251-23-0699',
 '595-70-6279',
 '338-95-1078',
 '633-45-7801',
 '785-98-1654',
 '504-69-5045',
 '198-10-5965',
 '672-26-3148',
 '379-18-2287',
 '697-68-2953',
 '135-35-5989',
 '297-77-3068',
 '527-82-5192',
 '663-78-4706',
 '797-10-6278',
 '174-63-5082',
 '648-65-2381',
 '472-17-0841',
 '705-45-4932',
 '131-87-3018',
 '633-30-2422',
 '290-68-0112',
 '817-23-8122',
 '687-35-1071',
 '315-21-3204',
 '105-46-1501',
 '315-12-8260',
 '680-18-1900',
 '609-34-0063',
 '181-86-3592',
 '733-09-6749',
 '599-97-6620',
 '671-60-9847',
 '543-56-9071',
 '293-53-7511',
 '443-23-2803',
 '534-92-4867',
 '523-69-8145',
 '134-55-7043',
 '601-89-5360',
 '449-85-9299',
 '499-27-6142',
 '671-23-7065',
 '757-68-0468',
 '570-25-4939',
 '481-70-6653',
 '693-64-9503',
 '643-16-3311',
 '318-44-9996',
 '582-60-7915',
 '219-09-8081',
 '267-26-2872',
 '861-22-5306',
 '279-54-2899',
 '176-49-9747',
 '488-77-5389',
 '378-41-1436',
 '152-90-1165',
 '386-23-6683',
 '887-93-2038',
 '496-36-5597',
 '820-48-6373',
 '120-82-0654',
 '387-80-4373',
 '886-60-6879',
 '833-48-8224',
 '203-40-0204',
 '423-31-0092',
 '786-13-2892',
 '301-65-2338',
 '170-54-8093',
 '279-21-2752',
 '665-55-7847',
 '398-14-1134',
 '724-79-8372',
 '437-40-9802',
 '456-16-6665',
 '536-61-8166',
 '103-37-4993',
 '843-24-1614',
 '527-21-0549',
 '503-30-4710',
 '204-07-1095',
 '124-27-3237',
 '593-80-0510',
 '145-01-5695',
 '888-05-4829',
 '831-10-4148',
 '746-22-9556',
 '676-64-6200',
 '772-27-6488',
 '378-21-1700',
 '147-09-0029',
 '518-18-0804',
 '392-96-7463',
 '104-77-9801',
 '373-31-8181',
 '218-34-4061',
 '450-07-2597',
 '658-81-4630',
 '181-62-1928',
 '570-39-0528',
 '876-27-9733',
 '760-99-9010',
 '875-11-7762',
 '864-03-3275',
 '481-38-8953',
 '581-34-5242',
 '881-59-4982',
 '313-38-4605',
 '403-37-0852',
 '238-40-2514',
 '841-37-8152',
 '181-46-4639',
 '667-89-1778',
 '240-12-7580',
 '739-81-7204',
 '471-81-5260',
 '860-96-0065',
 '835-66-0624',
 '188-97-1037',
 '688-64-7151',
 '626-46-5349',
 '832-79-8553',
 '471-11-4280',
 '344-70-5934',
 '487-30-6672',
 '550-85-8215',
 '653-60-5187',
 '501-71-7501',
 '280-37-1178',
 '388-12-8729',
 '372-26-6606',
 '721-35-1799',
 '552-32-6529',
 '124-70-4492',
 '283-27-8858',
 '764-18-3767',
 '467-13-7637',
 '130-82-5512',
 '866-49-2775',
 '539-22-4085',
 '893-24-0412',
 '443-75-4530',
 '727-55-0500',
 '542-47-6350',
 '444-48-6530',
 '100-43-4565',
 '803-73-3811',
 '349-45-1822',
 '821-18-4672',
 '123-40-9333',
 '832-75-4011',
 '308-01-4910',
 '609-89-8147',
 '288-90-5864',
 '775-17-8664',
 '563-35-5938',
 '816-90-3424',
 '728-58-1048',
 '850-16-1176',
 '718-03-1417',
 '544-68-5416',
 '731-76-5309',
 '830-21-4902',
 '133-06-0523',
 '616-94-2192',
 '487-36-8115',
 '647-30-5052',
 '496-04-8783',
 '524-29-5892',
 '895-85-4795',
 '123-92-5375',
 '592-42-2163',
 '340-08-5144',
 '299-72-8786',
 '315-72-8512',
 '170-10-1992',
 '633-23-5254',
 '333-47-3753',
 '434-89-7057',
 '301-75-1904',
 '871-44-6199',
 '576-27-2595',
 '886-68-7395',
 '742-88-0708',
 '753-49-2566',
 '503-32-2294',
 '679-87-8693',
 '873-05-5247',
 '506-69-7837',
 '744-09-0039',
 '568-81-3335',
 '441-09-0673',
 '342-81-1492',
 '645-58-4742',
 '186-52-8889',
 '180-55-6503',
 '656-84-5280',
 '506-21-9284',
 '812-75-8041',
 '884-99-2498',
 '500-66-2494',
 '498-01-2840',
 '404-27-0352',
 '655-22-7428',
 '319-37-9094',
 '293-47-8070',
 '542-55-2107',
 '550-46-7159',
 '320-58-4333',
 '621-52-0381',
 '594-20-8636',
 '125-38-9322',
 '825-81-7467',
 '807-33-9736',
 '829-83-3407',
 '395-62-0643',
 '426-70-6684',
 '260-26-8950',
 '313-76-9806',
 '144-48-6168',
 '331-66-9222',
 '525-50-1204',
 '841-87-7409',
 '474-50-6421',
 '310-44-5505',
 '552-01-5314',
 '282-29-5279',
 '106-33-0811',
 '603-68-2491',
 '186-48-8028',
 '530-90-6001',
 '862-82-9372',
 '445-31-1206',
 '457-68-2844',
 '429-67-0504',
 '314-58-2816',
 '662-87-6460',
 '733-07-8274',
 '335-50-3304',
 '529-30-4962',
 '733-64-6779',
 '699-60-4172',
 '213-43-4178',
 '620-90-5595',
 '376-93-8637',
 '499-69-3630',
 '568-33-6841',
 '696-51-2471',
 '397-72-0247',
 '412-08-8035',
 '542-73-9084',
 '738-31-6465',
 '505-36-9900',
 '427-73-1663',
 '283-15-9649',
 '701-52-7682',
 '716-42-9202',
 '530-85-2992',
 '331-12-3821',
 '521-62-3201',
 '195-52-3963',
 '672-06-4160',
 '577-65-3523',
 '651-87-4841',
 '334-44-5533',
 '387-52-4431',
 '413-91-6248',
 '448-14-4891',
 '216-43-4549',
 '491-91-0406',
 '803-54-7812',
 '872-83-5506',
 '762-51-4258',
 '403-05-5279',
 '607-87-3957',
 '697-28-1716',
 '603-62-4671',
 '364-22-1590',
 '587-59-0905',
 '737-79-7037',
 ...]

In [72]:
bitcoin = re.findall('bitcoin:(\w{5,})',s)

In [65]:
len(bitcoin)

2857

In [67]:
counter = 0
for n in bitcoin:
    if n ==  'null':
        counter+=1
        
counter

76

In [68]:
len(bitcoin) - counter

2781

In [73]:
len(bitcoin)

2781

In [74]:
streets = re.findall('\d+ \w+ \w+(?: \w+)*',s)

In [75]:
len(streets)

958

In [77]:
streets

['814 Monterey Court',
 '62 Hooker Park',
 '27811 Clyde Gallagher Drive',
 '32553 Riverside Pass',
 '17157 Clemons Alley',
 '75 Dorton Parkway',
 '5 Manitowish Trail',
 '84 Northland Center',
 '64404 Sundown Street',
 '47144 Mockingbird Street',
 '413 Sutherland Court',
 '8906 Almo Lane',
 '34223 Graceland Crossing',
 '94 Mcguire Lane',
 '1 Delladonna Circle',
 '169 Claremont Point',
 '19475 Meadow Vale Crossing',
 '147 Cascade Center',
 '762 Knutson Terrace',
 '301 Monument Trail',
 '39 Buena Vista Alley',
 '94 Barby Circle',
 '98 Hansons Road',
 '83525 Calypso Way',
 '61 Heath Street',
 '60 Bay Hill',
 '923 Lindbergh Place',
 '1 Elmside Circle',
 '34 High Crossing Road',
 '63 Bonner Lane',
 '67 Superior Terrace',
 '846 Acker Road',
 '4 Menomonie Avenue',
 '858 Arrowood Terrace',
 '2566 Anhalt Trail',
 '30840 Sherman Hill',
 '29170 Parkside Lane',
 '150 Logan Street',
 '74 North Court',
 '51374 8th Hill',
 '6432 Continental Avenue',
 '46916 Donald Court',
 '1950 Beilfuss Hill',
 '949 Park Meadow Park',
 '38 Tennyson Junction',
 '35 Melby Parkway',
 '55 Eggendart Circle',
 '36111 Drewry Pass',
 '3 Messerschmidt Crossing',
 '5 Hauk Terrace',
 '4335 Calypso Parkway',
 '3 Schurz Lane',
 '11 Haas Drive',
 '9639 Lindbergh Circle',
 '4 Coleman Road',
 '7751 Dahle Park',
 '699 Northport Hill',
 '754 Rockefeller Point',
 '38375 Anhalt Street',
 '4828 Carpenter Parkway',
 '5 Golden Leaf Street',
 '46594 Mallory Way',
 '6108 Sundown Junction',
 '92105 Melody Circle',
 '8635 Dennis Way',
 '7479 Rowland Terrace',
 '75 Buena Vista Center',
 '1 Michigan Junction',
 '3543 Leroy Trail',
 '47603 Doe Crossing Terrace',
 '3 Monterey Alley',
 '3 Cordelia Street',
 '4890 Center Junction',
 '12 Cardinal Road',
 '84 Haas Court',
 '46 Anthes Circle',
 '074 Erie Pass',
 '51827 Arkansas Crossing',
 '83992 Schurz Way',
 '3 Kenwood Way',
 '721 Golf Course Crossing',
 '2400 Farwell Way',
 '0 Sheridan Hill',
 '81427 Londonderry Alley',
 '8083 Melby Lane',
 '77851 Clyde Gallagher Road',
 '274 Colorado Drive',
 '4964 Johnson Drive',
 '453 Mesta Drive',
 '4 Cody Terrace',
 '74711 Moulton Avenue',
 '3410 Melrose Crossing',
 '6253 Cascade Trail',
 '289 South Place',
 '744 Marcy Road',
 '82060 Spenser Trail',
 '652 Roxbury Plaza',
 '57065 Dryden Trail',
 '91304 Dottie Junction',
 '10996 Schiller Alley',
 '1 Almo Plaza',
 '83 Starling Pass',
 '8423 Green Crossing',
 '3 Melody Lane',
 '7341 Linden Alley',
 '0 Columbus Hill',
 '20 Shopko Road',
 '77 Mayfield Way',
 '785 Lighthouse Bay Point',
 '6589 Forest Dale Way',
 '5 Loomis Street',
 '3 Randy Lane',
 '9 Towne Hill',
 '580 Lerdahl Street',
 '77 5th Circle',
 '3702 Ohio Center',
 '860 Marquette Alley',
 '11969 Fairview Lane',
 '770 Shopko Place',
 '997 Carpenter Plaza',
 '081 Mayer Lane',
 '5261 Maple Pass',
 '7 Swallow Road',
 '7612 Autumn Leaf Avenue',
 '8 Bellgrove Junction',
 '3 Helena Pass',
 '06 Loftsgordon Alley',
 '6402 Summer Ridge Court',
 '88 Vera Drive',
 '3162 Milwaukee Center',
 '0 Northland Park',
 '76307 Bashford Crossing',
 '54 Doe Crossing Point',
 '87 Pine View Way',
 '5574 Pine View Crossing',
 '17303 Ilene Circle',
 '8 Warner Court',
 '88400 New Castle Alley',
 '6 Continental Terrace',
 '7 Thompson Road',
 '6 Harbort Terrace',
 '11090 Almo Junction',
 '21261 Norway Maple Drive',
 '477 Carpenter Point',
 '3360 Express Avenue',
 '5908 Cardinal Hill',
 '913 Gina Trail',
 '8548 Boyd Junction',
 '5250 Sommers Point',
 '3 Green Ridge Parkway',
 '78146 Kenwood Park',
 '1376 Banding Plaza',
 '2206 Lawn Alley',
 '48279 Sullivan Avenue',
 '1 Badeau Drive',
 '55 Nelson Drive',
 '096 Chinook Lane',
 '82 Mayer Lane',
 '3857 Northland Crossing',
 '9 Dovetail Court',
 '198 Oxford Circle',
 '078 Mitchell Place',
 '11 Thompson Place',
 '8 Fair Oaks Place',
 '893 Doe Crossing Center',
 '96190 Sommers Pass',
 '768 Bultman Center',
 '288 Hintze Alley',
 '61 Anthes Park',
 '461 Ronald Regan Plaza',
 '10072 Shoshone Terrace',
 '711 Artisan Place',
 '6 Commercial Pass',
 '854 Coleman Place',
 '09411 Ramsey Way',
 '9633 Mifflin Lane',
 '75 Briar Crest Center',
 '24922 Gateway Pass',
 '93 Garrison Center',
 '189 Pearson Junction',
 '39898 Doe Crossing Terrace',
 '945 Forster Pass',
 '647 Rieder Parkway',
 '5 Parkside Terrace',
 '1 Trailsway Place',
 '2 Anthes Junction',
 '3891 Bonner Pass',
 '7915 Arapahoe Pass',
 '9 Rusk Way',
 '47278 Elgar Park',
 '8788 Pierstorff Way',
 '432 3rd Terrace',
 '00081 Crowley Place',
 '02 Lakewood Trail',
 '3874 Blackbird Street',
 '5328 Loomis Terrace',
 '237 Mitchell Parkway',
 '43526 Pepper Wood Place',
 '8 Leroy Road',
 '7 Troy Place',
 '78676 Prairieview Road',
 '6772 Ramsey Drive',
 '43 Calypso Point',
 '5504 Meadow Ridge Pass',
 '058 Forster Plaza',
 '992 Delladonna Crossing',
 '0543 Maple Wood Drive',
 '8608 Monument Junction',
 '1345 Goodland Court',
 '96 Garrison Drive',
 '6 Florence Circle',
 '503 Sugar Junction',
 '50869 Westerfield Pass',
 '2 Delladonna Avenue',
 '94665 Corscot Pass',
 '8485 Hanson Junction',
 '582 Thierer Park',
 '90 Fallview Center',
 '19756 Petterle Drive',
 '65 Artisan Hill',
 '4636 Welch Crossing',
 '25931 Vermont Road',
 '325 Superior Alley',
 '01 Armistice Circle',
 '41 Morning Crossing',
 '0218 Daystar Circle',
 '57823 Harper Trail',
 '732 Pearson Circle',
 '93 Fuller Place',
 '9797 Steensland Court',
 '54 Rowland Road',
 '9509 Dennis Alley',
 '84 Northridge Park',
 '378 Talmadge Terrace',
 '33140 Southridge Center',
 '31 La Follette Circle',
 '2568 Warner Court',
 '21 Pawling Street',
 '774 Northland Junction',
 '6303 Di Loreto Drive',
 '9 Longview Plaza',
 '461 Anderson Avenue',
 '05 Lawn Park',
 '070 Village Avenue',
 '2 Hermina Court',
 '873 Nova Circle',
 '542 International Park',
 '04 Michigan Street',
 '0892 Maywood Point',
 '7745 Susan Trail',
 '9218 Burrows Court',
 '72142 Gulseth Terrace',
 '3832 Oxford Way',
 '278 Forest Dale Court',
 '91091 5th Center',
 '89128 Fordem Hill',
 '3797 Fuller Place',
 '04115 Darwin Avenue',
 '3264 Village Court',
 '0445 Oneill Alley',
 '95405 Becker Place',
 '05 Columbus Lane',
 '1 Hudson Parkway',
 '5 Westport Lane',
 '27 Prentice Place',
 '12 South Pass',
 '786 Ludington Plaza',
 '06505 Lakeland Road',
 '99 Shelley Court',
 '13179 Dottie Point',
 '058 Thierer Terrace',
 '7 Roxbury Pass',
 '192 Holy Cross Plaza',
 '829 Northfield Terrace',
 '96305 Butterfield Drive',
 '4308 Kropf Trail',
 '10549 Kipling Park',
 '290 Stuart Street',
 '93016 Meadow Ridge Plaza',
 '8955 Harper Crossing',
 '480 Barby Place',
 '571 Rowland Street',
 '805 Harper Terrace',
 '3 Nevada Hill',
 '7 Nova Road',
 '7 Macpherson Circle',
 '97541 Kropf Court',
 '13 Commercial Parkway',
 '4494 Golf Course Terrace',
 '93860 Eagan Avenue',
 '2 Eastlawn Lane',
 '1931 Fallview Way',
 '3 Waywood Way',
 '58196 Green Alley',
 '7958 Elka Circle',
 '02487 Carberry Trail',
 '95025 Moose Drive',
 '4599 Meadow Ridge Circle',
 '6592 8th Point',
 '47 Northwestern Hill',
 '4648 Vahlen Trail',
 '5 Transport Road',
 '16544 Fremont Alley',
 '98 Briar Crest Alley',
 '8 Melody Way',
 '8752 Oxford Street',
 '84 Ridge Oak Plaza',
 '63 Spenser Center',
 '9 Tennyson Road',
 '3 Sauthoff Road',
 '21 Maple Wood Place',
 '7526 Aberg Park',
 '367 Prentice Park',
 '0 Badeau Drive',
 '948 Northview Hill',
 '752 Vermont Place',
 '99628 Glacier Hill Road',
 '33 Londonderry Lane',
 '6767 Boyd Alley',
 '860 Northfield Lane',
 '0552 Ludington Lane',
 '96 Lawn Plaza',
 '3 Corben Center',
 '1 Algoma Avenue',
 '8924 Porter Parkway',
 '67 Springs Plaza',
 '892 Sugar Avenue',
 '590 Park Meadow Way',
 '7440 Grayhawk Park',
 '67 Loftsgordon Street',
 '9863 Shopko Point',
 '1 Upham Junction',
 '3566 Nobel Avenue',
 '9 Mosinee Center',
 '45 Muir Trail',
 '347 Roth Junction',
 '9 Sauthoff Circle',
 '49708 Myrtle Center',
 '40 Hintze Place',
 '29756 Cottonwood Lane',
 '53 Derek Point',
 '51 Crowley Hill',
 '7 Cardinal Place',
 '91 Chive Circle',
 '225 Fieldstone Park',
 '6 Helena Junction',
 '69690 Kennedy Circle',
 '2 Lukken Center',
 '335 Mallard Way',
 '499 Prairie Rose Alley',
 '350 Nevada Circle',
 '9392 Fremont Place',
 '858 Tennyson Way',
 '082 Katie Circle',
 '852 Evergreen Street',
 '422 Jackson Street',
 '93 Dunning Center',
 '13563 Kinsman Plaza',
 '12 Blackbird Alley',
 '89 Lakeland Place',
 '588 Bellgrove Road',
 '6 Fuller Park',
 '92611 Scoville Terrace',
 '8 Dunning Court',
 '296 Eliot Center',
 '1 Loftsgordon Drive',
 '790 Express Drive',
 '81730 Sauthoff Road',
 '5 Lunder Avenue',
 '9 Warrior Hill',
 '06 Fairfield Parkway',
 '644 Parkside Lane',
 '25214 Meadow Vale Court',
 '98 Cambridge Terrace',
 '81644 Blaine Point',
 '1442 Moulton Circle',
 '5 Crest Line Crossing',
 '369 Warner Center',
 '4753 Farwell Trail',
 '594 Southridge Center',
 '6509 Lakewood Gardens Place',
 '235 Lien Court',
 '581 Clove Hill',
 '3 Canary Pass',
 '93685 Kedzie Terrace',
 '0057 Coolidge Place',
 '2923 Spohn Terrace',
 '33 Melody Center',
 '805 Amoth Junction',
 '9 Sloan Point',
 '82094 Del Mar Place',
 '4925 Redwing Trail',
 '743 Nancy Way',
 '918 Lunder Court',
 '2 Duke Avenue',
 '0 Holy Cross Point',
 '23795 Hermina Crossing',
 '56 Boyd Parkway',
 '96 Atwood Junction',
 '94 Village Green Parkway',
 '3 Mallard Circle',
 '322 Texas Drive',
 '0831 Burrows Drive',
 '63686 Northfield Alley',
 '03 North Place',
 '923 Merry Terrace',
 '6073 Harbort Junction',
 '100 Londonderry Avenue',
 '5369 Fairview Alley',
 '942 Oxford Court',
 '7 Mariners Cove Alley',
 '06935 Alpine Drive',
 '68282 High Crossing Way',
 '91661 Hanover Lane',
 '8 Ridgeway Road',
 '397 Sage Junction',
 '66 Green Avenue',
 '8969 Norway Maple Crossing',
 '558 Dwight Trail',
 '274 Cardinal Terrace',
 '12197 Anhalt Street',
 '3161 Cardinal Circle',
 '58139 Butternut Road',
 '8265 Jackson Avenue',
 '322 Memorial Circle',
 '1 Fieldstone Center',
 '16485 Troy Plaza',
 '60 Sunfield Terrace',
 '02175 Old Gate Trail',
 '0871 Barnett Way',
 '0243 Arrowood Junction',
 '3 Summerview Street',
 '8758 Dorton Trail',
 '6 Lakewood Gardens Place',
 '7381 Summit Center',
 '13146 Crowley Court',
 '98842 Continental Terrace',
 '67 Lyons Terrace',
 '5300 Victoria Terrace',
 '25 Anzinger Way',
 '938 Eliot Center',
 '956 Pond Junction',
 '21736 Doe Crossing Center',
 '05 Carberry Center',
 '9866 Memorial Plaza',
 '5219 Vidon Crossing',
 '53 Lyons Parkway',
 '2 Everett Drive',
 '50391 Nancy Junction',
 '57147 Armistice Plaza',
 '5734 Kipling Terrace',
 '3199 Golden Leaf Hill',
 '686 Red Cloud Point',
 '889 Mitchell Park',
 '92 Monica Lane',
 '1200 Shoshone Center',
 '50551 Muir Park',
 '1 Crownhardt Lane',
 '01256 Sachs Junction',
 '2620 Scofield Hill',
 '3809 Briar Crest Hill',
 '950 Mosinee Way',
 '959 Dawn Junction',
 '858 Mesta Alley',
 '6 Wayridge Junction',
 '5 Coolidge Alley',
 '330 Anhalt Trail',
 '1782 Donald Street',
 '668 2nd Circle',
 '21631 Fisk Terrace',
 '5 Melody Hill',
 '9 Brickson Park Center',
 '8 Aberg Terrace',
 '83676 Nobel Junction',
 '1766 Crownhardt Junction',
 '8 Gina Crossing',
 '14 Anderson Crossing',
 '16 Blue Bill Park Park',
 '67453 Kipling Center',
 '9 8th Hill',
 '5 Melrose Terrace',
 '9462 Pleasure Plaza',
 '50277 Browning Park',
 '889 David Alley',
 '46 Lunder Crossing',
 '8582 Judy Crossing',
 '528 Westend Drive',
 '4 Spohn Court',
 '67143 Briar Crest Court',
 '6972 Buell Center',
 '1243 Sunbrook Street',
 '6 Memorial Lane',
 '0 Butternut Alley',
 '626 Vidon Crossing',
 '8711 Dexter Drive',
 '218 Maple Wood Drive',
 '1 Fieldstone Center',
 '31792 Spaight Crossing',
 '270 Pepper Wood Pass',
 '77 Arapahoe Hill',
 '5560 West Park',
 '142 Lakewood Gardens Trail',
 '86318 Memorial Trail',
 '5042 Mallory Crossing',
 '8892 Thompson Lane',
 '6 Manufacturers Pass',
 '1 Killdeer Park',
 '87254 Fulton Road',
 '1834 Eastwood Lane',
 '82436 1st Way',
 '7 Ridge Oak Avenue',
 '6 Rutledge Plaza',
 '7663 8th Road',
 '897 Moulton Lane',
 '399 Village Green Parkway',
 '24404 6th Drive',
 '126 Glacier Hill Road',
 '057 Mockingbird Road',
 '24 Coolidge Pass',
 '8647 Surrey Way',
 '8 Daystar Way',
 '30 Sunbrook Parkway',
 '099 Roxbury Park',
 '28 Center Circle',
 '457 Dawn Hill',
 '52009 Doe Crossing Drive',
 '66 Ridgeview Junction',
 '94 Barnett Plaza',
 '26911 Service Road',
 '0 Di Loreto Trail',
 '242 Elmside Terrace',
 '71219 Portage Terrace',
 '276 1st Point',
 '28 Golden Leaf Drive',
 '91614 Washington Center',
 '34 Becker Road',
 '5981 Farragut Way',
 '8 Pleasure Street',
 '9600 Elmside Place',
 '7132 Oak Valley Road',
 '68 Acker Place',
 '570 Ohio Pass',
 '1 Brown Avenue',
 '344 Heffernan Way',
 '9 Maple Junction',
 '46 Gina Way',
 '70 Golden Leaf Trail',
 '26 Mosinee Circle',
 '02618 Blaine Park',
 '9 Londonderry Pass',
 '2 Havey Way',
 '74 Hudson Terrace',
 '92 Marquette Avenue',
 '6 Golden Leaf Terrace',
 '20979 Transport Drive',
 '6 Bartillon Junction',
 '3 Dakota Road',
 '58658 David Circle',
 '8 Thackeray Lane',
 '6063 Mccormick Way',
 '25 Sugar Point',
 '4 Meadow Valley Plaza',
 '13937 Westend Alley',
 '30373 Parkside Center',
 '75364 Fordem Way',
 '0 Pepper Wood Terrace',
 '34217 Mosinee Crossing',
 '54 Butternut Hill',
 '9301 3rd Drive',
 '325 Nancy Pass',
 '0 Moose Way',
 '311 Stuart Plaza',
 '80182 Fairfield Park',
 '247 Montana Parkway',
 '23298 Sauthoff Plaza',
 '2412 Maryland Road',
 '22859 Crescent Oaks Park',
 '287 Eagan Terrace',
 '0 Nelson Crossing',
 '006 Burrows Pass',
 '7 Cordelia Junction',
 '60 Clove Center',
 '238 Vera Court',
 '0915 Almo Crossing',
 '82 Shopko Parkway',
 '58 Manley Junction',
 '841 Katie Place',
 '4305 Mandrake Pass',
 '6120 Columbus Circle',
 '79320 Nevada Place',
 '4 Briar Crest Plaza',
 '70270 Lunder Alley',
 '4 Green Avenue',
 '85229 Pawling Point',
 '762 Fisk Parkway',
 '8 Browning Terrace',
 '821 Buhler Place',
 '52964 Kedzie Avenue',
 '97 Basil Trail',
 '35 Raven Avenue',
 '8179 Arkansas Court',
 '21365 Crest Line Trail',
 '19 Hovde Court',
 '7796 Derek Place',
 '6107 Spohn Crossing',
 '5 Carpenter Alley',
 '2 Northport Pass',
 '7 Esker Point',
 '36 Northview Point',
 '01669 Harbort Crossing',
 '7 Starling Avenue',
 '2 Maywood Parkway',
 '76877 Donald Way',
 '3 Rusk Trail',
 '5 Stang Road',
 '763 Anzinger Center',
 '27 Ruskin Hill',
 '7818 Hintze Road',
 '6953 Mesta Street',
 '44 Park Meadow Trail',
 '7200 3rd Hill',
 '0003 Riverside Court',
 '914 8th Alley',
 '7 Duke Lane',
 '71142 Mccormick Place',
 '016 Bluejay Pass',
 '2 Morningstar Crossing',
 '9 Briar Crest Alley',
 '96135 Dahle Plaza',
 '1725 Mallory Plaza',
 '93732 Waubesa Street',
 '629 Meadow Ridge Avenue',
 '23101 Anthes Point',
 '8342 Jenifer Alley',
 '0049 Clemons Circle',
 '499 Scofield Court',
 '32 Bultman Point',
 '843 Buhler Circle',
 '9842 Dapin Drive',
 '160 Declaration Center',
 '7 Southridge Trail',
 '5223 Sunfield Avenue',
 '01 Mosinee Trail',
 '51747 Schlimgen Hill',
 '7540 Fallview Lane',
 '78013 Holmberg Plaza',
 '126 Menomonie Center',
 '8700 Portage Circle',
 '6 Homewood Crossing',
 '251 Sunnyside Parkway',
 '9 Northridge Crossing',
 '11 Moland Road',
 '45 Darwin Hill',
 '9 Magdeline Avenue',
 '41 Novick Pass',
 '32138 Myrtle Plaza',
 '76 Golf Way',
 '1172 Pierstorff Court',
 '60321 Londonderry Parkway',
 '6 Maryland Park',
 '5 Spenser Plaza',
 '5908 Chinook Place',
 '65551 Westend Avenue',
 '364 Beilfuss Crossing',
 '3992 Memorial Way',
 '7 Briar Crest Parkway',
 '934 Farragut Road',
 '71374 Manufacturers Point',
 '568 Sauthoff Trail',
 '81063 Dorton Junction',
 '43313 Sutherland Court',
 '4318 Susan Place',
 '7678 Marcy Crossing',
 '3 Larry Avenue',
 '07 Riverside Crossing',
 '29 Talmadge Terrace',
 '40 Rusk Park',
 '1 Village Terrace',
 '57856 Mariners Cove Trail',
 '548 Pearson Pass',
 '4 Sherman Court',
 '547 Crownhardt Crossing',
 '87222 Basil Alley',
 '43 Ruskin Court',
 '04 Paget Parkway',
 '11 Utah Trail',
 '203 Columbus Alley',
 '38946 Del Sol Park',
 '0 Valley Edge Park',
 '6 Thompson Way',
 '628 Colorado Point',
 '2737 Eastwood Avenue',
 '9 Morning Park',
 '98 Glendale Trail',
 '47 Clarendon Court',
 '94 Westridge Terrace',
 '51425 Del Mar Point',
 '242 Hayes Pass',
 '6973 Saint Paul Point',
 '0022 Spohn Junction',
 '7 Farwell Pass',
 '7948 Canary Junction',
 '1 Clove Alley',
 '78274 Ohio Lane',
 '067 Stone Corner Trail',
 '23 Steensland Way',
 '9 Gulseth Circle',
 '40918 Sheridan Center',
 '45 Waywood Point',
 '2 Onsgard Parkway',
 '2334 Annamark Center',
 '5669 Myrtle Alley',
 '52768 Union Plaza',
 '32378 Shopko Lane',
 '8 Bunting Point',
 '9508 Hazelcrest Point',
 '91326 Roth Pass',
 '33 Linden Court',
 '37 American Ash Way',
 '5 Mayer Pass',
 '2 Springs Road',
 '4318 Service Circle',
 '31905 Weeping Birch Court',
 '640 Sage Way',
 '5 Green Way',
 '181 Warner Place',
 '1 Loomis Park',
 '2073 Summerview Way',
 '7019 Vermont Park',
 '281 Raven Way',
 '52014 Crownhardt Lane',
 '50 Sachs Terrace',
 '33 Carey Crossing',
 '27 Loeprich Point',
 '60387 Ryan Pass',
 '05486 Bluejay Drive',
 '4 Messerschmidt Point',
 '2 Carpenter Crossing',
 '884 Monument Road',
 '6 Warbler Place',
 '6 Utah Hill',
 '776 Ridgeview Avenue',
 '22 Burrows Terrace',
 '38363 Jenna Street',
 '73925 Menomonie Plaza',
 '0 South Alley',
 '872 Burrows Crossing',
 '22375 Clove Plaza',
 '8 Hauk Crossing',
 '1 Morningstar Crossing',
 '6156 Laurel Way',
 '413 Merchant Pass',
 '83 North Way',
 '0 Chinook Way',
 '940 Fisk Drive',
 '487 Bartelt Park',
 '48314 Homewood Alley',
 '5012 Comanche Road',
 '73046 Oriole Lane',
 '5 Pleasure Terrace',
 '53642 Del Mar Alley',
 '7499 Fairfield Junction',
 '72 Northland Drive',
 '962 Spohn Terrace',
 '0620 Esker Road',
 '12055 Village Alley',
 '40875 West Avenue',
 '2 4th Alley',
 '4 Delladonna Center',
 '93173 West Point',
 '8783 Parkside Junction',
 '7706 Memorial Court',
 '86590 Manufacturers Road',
 '818 Delaware Avenue',
 '66 Schurz Circle',
 '210 Manufacturers Junction',
 '2 Leroy Court',
 '97528 Thompson Terrace',
 '432 Barnett Street',
 '4 Sundown Crossing',
 '1 Algoma Crossing',
 '564 Toban Pass',
 '950 Fulton Hill',
 '0271 Menomonie Avenue',
 '195 Luster Avenue',
 '85 Moland Point',
 '88987 Paget Parkway',
 '4340 Elgar Park',
 '832 Kings Place',
 '7 Jay Point',
 '96 Northridge Trail',
 '82 Buena Vista Pass',
 '6 Brickson Park Center',
 '41392 Nancy Avenue',
 '0267 Harbort Crossing',
 '69 Dennis Circle',
 '261 Westport Junction',
 '1155 Vermont Center',
 '732 Butterfield Plaza',
 '161 Fuller Street',
 '03 Blue Bill Park Hill',
 '12 Lillian Center',
 '14361 Packers Terrace',
 '9 Burrows Drive',
 '24256 Stang Circle',
 '7 Erie Junction',
 '532 Bay Plaza',
 '3128 Pepper Wood Point',
 '3328 Novick Plaza',
 '6837 Knutson Hill',
 '675 Manley Street',
 '86389 Monica Center',
 '74694 Farragut Circle',
 '90 Anhalt Road',
 '89701 Kennedy Court',
 '34770 Mendota Lane',
 '5316 Old Gate Drive',
 '49608 Dryden Court',
 '95116 Westerfield Alley',
 '0 Lawn Road',
 '131 Southridge Circle',
 '7 Kropf Plaza',
 '77 Amoth Crossing',
 '458 Cascade Street',
 '2 Miller Crossing',
 '88 Vidon Road',
 '808 Ramsey Terrace',
 '96 Kedzie Street',
 '06 Algoma Terrace',
 '260 Fair Oaks Alley',
 '93 Dayton Place',
 '55296 Gateway Avenue',
 '1 Larry Plaza',
 '6 Chinook Way',
 '019 Burrows Way',
 '4 Larry Street',
 '04653 Porter Alley',
 '6 Esch Lane',
 '1 Portage Place',
 '4 Crescent Oaks Alley',
 '20616 Canary Pass',
 '71349 Carpenter Street',
 '139 Fremont Street',
 '0303 Buhler Drive',
 '7 Swallow Circle',
 '141 David Parkway',
 '74 Fremont Pass',
 '3620 Bartillon Parkway',
 '7932 Melvin Center',
 '49 Grasskamp Terrace',
 '2768 Waubesa Court',
 '50991 Doe Crossing Circle',
 '383 Autumn Leaf Alley',
 '42860 Clove Parkway',
 '587 Gateway Avenue',
 '43603 Nobel Place',
 '35383 Surrey Center',
 '58410 Mesta Lane',
 '214 Hollow Ridge Parkway',
 '276 Hagan Hill',
 '374 Superior Pass',
 '0945 Mitchell Center',
 '35379 Forster Lane',
 '0425 Melrose Avenue',
 '6297 Barby Avenue',
 '2216 Harbort Point',
 '87988 Wayridge Circle',
 '0 Mccormick Center',
 '471 Almo Lane',
 '028 Drewry Street',
 '06190 Scott Plaza',
 '67767 Merry Center',
 '86 Bunting Pass',
 '312 Portage Point',
 '2901 Haas Drive',
 '52282 Orin Way',
 '958 Butternut Point',
 '778 South Center',
 '6 Hoepker Crossing',
 '152 Prairieview Center',

In [78]:
# don't change this cell, but do run it -- it is needed for the tests
test_fp = os.path.join('data', 'messy.test.txt')
test_s = open(test_fp, encoding='utf8').read()
emails, ssn, bitcoin, addresses = extract_personal(test_s)

In [79]:
grader.check("q2")

q2 results: All test cases passed!

## Question 3 ‚Äì TF-IDF üìä

The dataset `data/reviews.txt` contains [Amazon reviews](http://jmcauley.ucsd.edu/data/amazon/) for ~200k phones and phone accessories. The dataset has already been "cleaned" for you. In this question, you will create a function that takes in the reviews dataset as a Series (with one entry per review) as well as a single review, and returns the word that "best summarizes the single review" using TF-IDF.

To do so, implement the two functions below.

#### `tfidf_data`

Create a function `tfidf_data` that takes in the reviews data as a Series (`reviews_ser`) and a single review (`review`) and returns a DataFrame indexed by the words in `review` with four columns:
- `'cnt'`: the number of times each word is found in the review 
- `'tf'`: the term frequency for each word
- `'idf'`: the inverse document frequency for each word
- `'tfidf'` the TF-IDF for each word

You may use a `for`-loop. The words in the outputted DataFrame may appear in any order.

***Hint:*** You may need to use the [`'\b'` character](https://www.regular-expressions.info/wordboundaries.html) somewhere.
    
<br>

#### `relevant_word`

Create a function `tfidf_data` that takes in the DataFrame that `tfidf_data` returns and returns the word that "best summarizes" the review. If there are multiple "best" summary words, return any one of them.

In [119]:
# experiment with tfidf_data using reviews_ser and review below 
fp = os.path.join('data', 'reviews.txt')
reviews_ser = pd.read_csv(fp, header=None, squeeze=True)
review = open(os.path.join('data', 'review.txt'), encoding='utf8').read().strip()

/tmp/ipykernel_6664/627512756.py:3: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  reviews_ser = pd.read_csv(fp, header=None, squeeze=True)

In [149]:
reviews_ser

0        works great  i called t mobile and had this si...
1        these items looked to be of good quality and h...
2        this product arrive faster than i expected  i ...
3        i brought this for my sister who has a g2 but ...
4         i am both delighted and disappointed with del...
                               ...
58297    bought i for my husband's phone a week ago  ni...
58298    the spring loaded adjustable holder looks nift...
58299    received on time  everything working less spea...
58300    i bought this battery pack with the mindset of...
58301              that work    but thats not the original
Name: 0, Length: 58302, dtype: object

In [83]:
review

'this is a great new case design that i have not seen before it has a slim silicone skin that really locks in the phone to cover and protect your phone from spills and such and also a hard polycarbonate outside shell cover to guard it against damage  this case also comes with different interchangeable skins and covers to create multiple color combinations  this is a different kind of case than the usual chunk of plastic  it is innovative and suits the iphone 5 perfectly'

In [158]:
words = pd.Series(re.findall(r'\b\w+\b',review)).value_counts()
data = pd.DataFrame(columns = ['cnt', 'tf', 'idf', 'tfidf'])
data['cnt'] = words
data['tf'] = data['cnt'] / data['cnt'].sum()
data


idfs = []
for n in words.index:
    idfs.append(np.log(len(reviews_ser) / reviews_ser.str.contains(n).sum()))


data['idf'] = idfs
data['tfidf'] = data['tf'] * data['idf']
#len(words)

In [159]:
tfidf_data()

                 cnt        tf       idf     tfidf
and                5  0.058824  0.219198  0.012894
a                  4  0.047059  0.003041  0.000143
this               3  0.035294  0.440309  0.015540
is                 3  0.035294  0.194456  0.006863
to                 3  0.035294  0.251689  0.008883
it                 3  0.035294  0.081721  0.002884
the                3  0.035294  0.119618  0.004222
case               3  0.035294  1.059063  0.037379
that               2  0.023529  0.839864  0.019762
also               2  0.023529  1.922164  0.045227
of                 2  0.023529  0.608500  0.014318
cover              2  0.023529  2.269387  0.053397
phone              2  0.023529  0.563087  0.013249
different          2  0.023529  2.932945  0.069010
with               1  0.011765  0.767949  0.009035
covers             1  0.011765  3.742829  0.044033
interchangeable    1  0.011765  6.591365  0.077545
skins              1  0.011765  6.603944  0.077693
comes              1  0.011765  2.767354  0.032557
damage             1  0.011765  3.924137  0.046166
color              1  0.011765  2.422764  0.028503
create             1  0.011765  5.135661  0.060420
multiple           1  0.011765  4.214136  0.049578
guard              1  0.011765  5.904487  0.069465
combinations       1  0.011765  7.259820  0.085410
kind               1  0.011765  3.137022  0.036906
than               1  0.011765  1.647404  0.019381
usual              1  0.011765  3.807126  0.044790
chunk              1  0.011765  6.814509  0.080171
plastic            1  0.011765  2.725910  0.032070
innovative         1  0.011765  7.102191  0.083555
suits              1  0.011765  7.335806  0.086304
iphone             1  0.011765  1.810353  0.021298
5                  1  0.011765  1.762052  0.020730
against            1  0.011765  4.266529  0.050194
such               1  0.011765  3.536774  0.041609
shell              1  0.011765  4.287531  0.050442
outside            1  0.011765  4.188935  0.049282
great              1  0.011765  1.285266  0.015121
new                1  0.011765  2.444468  0.028758
design             1  0.011765  2.741483  0.032253
i                  1  0.011765  0.002679  0.000032
have               1  0.011765  0.945344  0.011122
not                1  0.011765  0.777608  0.009148
seen               1  0.011765  4.095065  0.048177
before             1  0.011765  2.816021  0.033130
has                1  0.011765  1.341319  0.015780
slim               1  0.011765  3.504308  0.041227
silicone           1  0.011765  4.346674  0.051137
skin               1  0.011765  4.103338  0.048275
really             1  0.011765  1.895783  0.022303
locks              1  0.011765  5.616805  0.066080
in                 1  0.011765  0.173245  0.002038
protect            1  0.011765  1.462132  0.017202
your               1  0.011765  1.650348  0.019416
from               1  0.011765  1.604425  0.018876
spills             1  0.011765  7.606096  0.089483
hard               1  0.011765  2.415633  0.028419
polycarbonate      1  0.011765  6.430097  0.075648
perfectly          1  0.011765  2.754335  0.032404

In [117]:
tf = []
for n in words:
    count = len(re.findall(fr'\b{n}\b', review))
    tf.append(count)
data['cnt'] = pd.Series(index = words, data = tf)
data['tf'] = data['cnt'] / data.shape[0]

num_t_appear = []

for n in reviews_ser:
    print(re.findall(fr'\b\w+\b',n))

['works', 'great', 'i', 'called', 't', 'mobile', 'and', 'had', 'this', 'sim', 'card', 'activated', 'in', '5', 'minutes', 'they', 'have', 'a', 'automated', 'system', 'or', 'you', 'can', 'speak', 'to', 'a', 'rep']
['these', 'items', 'looked', 'to', 'be', 'of', 'good', 'quality', 'and', 'have', 'lasted', 'several', 'months', 'so', 'far', 'i', 'am', 'satisfied', 'with', 'the', 'purchase', 'considering', 'the', 'low', 'cost']

In [107]:
data = pd.DataFrame(index = words,columns = ['cnt', 'tf', 'idf', 'tfidf'])
data

           cnt   tf  idf tfidf
this       NaN  NaN  NaN   NaN
is         NaN  NaN  NaN   NaN
a          NaN  NaN  NaN   NaN
great      NaN  NaN  NaN   NaN
new        NaN  NaN  NaN   NaN
...        ...  ...  ...   ...
suits      NaN  NaN  NaN   NaN
the        NaN  NaN  NaN   NaN
iphone     NaN  NaN  NaN   NaN
5          NaN  NaN  NaN   NaN
perfectly  NaN  NaN  NaN   NaN

[85 rows x 4 columns]

In [160]:
fp = os.path.join('data', 'reviews.txt')
reviews_ser = pd.read_csv(fp, header=None, squeeze=True)
review = open(os.path.join('data', 'review.txt'), encoding='utf8').read().strip()
q3_tfidf = tfidf_data(reviews_ser, review)

/tmp/ipykernel_6664/590037031.py:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  reviews_ser = pd.read_csv(fp, header=None, squeeze=True)

In [171]:
q3_tfidf['tfidf'].sort_values(ascending=False).index[0]

'spills'

In [172]:
relevant_word(q3_tfidf)

'spills'

In [92]:
data

           cnt   tf  idf tfidf
this       NaN  NaN  NaN   NaN
is         NaN  NaN  NaN   NaN
a          NaN  NaN  NaN   NaN
great      NaN  NaN  NaN   NaN
new        NaN  NaN  NaN   NaN
...        ...  ...  ...   ...
suits      NaN  NaN  NaN   NaN
the        NaN  NaN  NaN   NaN
iphone     NaN  NaN  NaN   NaN
5          NaN  NaN  NaN   NaN
perfectly  NaN  NaN  NaN   NaN

[88 rows x 4 columns]

In [130]:
unique_words = pd.Series(re.findall(r'\b\w+\b',review).sum()).value_counts()
unique_words

AttributeError: 'list' object has no attribute 'sum'

In [173]:
# don't change this cell, but do run it -- it is needed for the tests
fp = os.path.join('data', 'reviews.txt')
reviews_ser = pd.read_csv(fp, header=None, squeeze=True)
review = open(os.path.join('data', 'review.txt'), encoding='utf8').read().strip()
q3_tfidf = tfidf_data(reviews_ser, review)

try:
    q3_rel = relevant_word(q3_tfidf)
except:
    q3_rel = None

/tmp/ipykernel_6664/2586003083.py:3: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  reviews_ser = pd.read_csv(fp, header=None, squeeze=True)

In [174]:
grader.check("q3")

q3 results: All test cases passed!

## Questions 4 and 5 ‚Äì Tweet Analysis üê•

The dataset `data/ira.csv` contains tweets tagged by Twitter as likely being posted by the [Internet Research Agency](https://en.wikipedia.org/wiki/Internet_Research_Agency), the tweet factory facing allegations for attempting to influence US political elections.

Questions 4 and 5 will focus on the following:
- Question 4: Look at the hashtags present in the text and trends in their makeup.
- Question 5: Prepare the dataset for modeling by creating features out of the text fields.

### Question 4 ‚Äì Hashtags #Ô∏è‚É£

You may assume that a hashtag is any string without whitespace that immediately follows a `'#'`.

#### `hashtag_list`

Create a function `hashtag_list` that takes in a Series of tweet texts and returns a Series containing a list of hashtags present in each tweet's text. If a tweet's text doesn't contain a hashtag, the Series should contain an empty list for that tweet. Don't include the `'#'` symbol in the lists that are returned (see the doctest for an example).

<br>

#### `most_common_hashtag`

Create a function `most_common_hashtag` that takes in a Series of hashtag lists (as is outputted by `hashtag_list`) and returns a Series consisting of a single hashtag per tweet: 
- If the tweet's text has no hashtags, the entry should in the output Series should be `NaN`.
- If the tweet's text has one distinct hashtag, the entry in the output Series should be that hashtag.
- If the tweet's text has more than one hashtag, the entry in the output Series should be be the most common hashtag **in the whole input Series**. If there is a tie for most common, any of the most common can be returned.
    - For example, if the input Series was `pd.Series([[2], [2], [3, 2, 3]])`, the output would be `pd.Series([2, 2, 2])`. Even though `3` was more common in the third list than `2`, `2` is the most common among all hashtags in the Series.

In [209]:
# The doctests/public tests don't test your work on the `ira` data,
# but the hidden tests do.
# So, make sure to thoroughly test your work yourself!
fp = os.path.join('data', 'ira.csv')
ira = pd.read_csv(fp, names=['id', 'name', 'date', 'text'])

In [185]:
hashes_ser = ira['text'].apply(lambda x:  re.findall('#([^\s]+)',x))
hashes_ser

0        [Exercise, LoseBellyFat, CatTV, TeenWolf‚Ä¶]
1                                                []
2                                            [tech]
3                                            [news]
4           [IHatePokemonGoBecause, PokesAreJokes.]
                            ...
89995                                    [politics]
89996                         [ThingsYouCantIgnore]
89997                                            []
89998                                [rantfortoday]
89999                                        [news]
Name: text, Length: 90000, dtype: object

In [207]:
hashes_ser[8]

['NowPlaying:', 'rap', 'hiphop', 'music']

In [208]:
hashes_counts.loc[hashes_ser[8]]

NowPlaying:    70
rap            37
hiphop         47
music          49
Name: text, dtype: int64

In [206]:
hashes_counts.loc[hashes_ser[8]].idxmax()

'NowPlaying:'

In [203]:
most_common_hashtag(hashes_ser)[8]

'NowPlaying:'

In [196]:
hashes_ser[0]

['Exercise', 'LoseBellyFat', 'CatTV', 'TeenWolf‚Ä¶']

In [199]:
hashes_counts = hashes_ser.explode().value_counts()
hashes_counts

hashes_counts.loc[hashes_ser[0]].idxmax()

'CatTV'

In [ ]:

for n in hashes_ser:
    if len(hashes_ser) == 0:
        return np.nan
    elif len(hashes_ser) == 1:
        return hashes_ser[0]
    else:
        hashes_counts = hashes_ser.explode().value_counts()
        #hashes_counts
        hashes_counts.loc[n].idxmax()

In [186]:
len([])

0

In [180]:
ira.iloc[49197]

id                                                3991390
name                                       Messiah Haynes
date                                     2016-07-18 11:00
text    RT @adamoc132013: #IDoOkForSomeoneWho has no m...
Name: 49197, dtype: object

In [210]:
grader.check("q4")

q4 results: All test cases passed!

### Question 5 ‚Äì Features üìã

Now, create a DataFrame of features from the `ira` data.  That is, create a function `create_features` that takes in a DataFrame `ira` that has just a single column, `'text'`, and returns a DataFrame with the same index as `ira` (i.e. the rows correspond to the same tweets) and the following columns:
* `'num_hashtags'`, the number of hashtags present in the tweet.
* `'mc_hashtags'`, the most common hashtag associated to the tweet (using the result of `most_common_hashtag` from Question 4).
* `'num_tags'`, the number of tags the tweet has (look for the presence of `'@'`).
* `'num_links'`, the number of hyperlinks present in the tweet.
    - A hyperlink is a string starting with `'http://'` or `'https://'`, not followed by whitespaces.
* `'is_retweet'`, a Boolean describing whether the tweet is a retweet. A retweet is a tweet that **begins** with `'RT'`.
* `'text'`, a version of the tweet's text that is cleaned according to the following steps, **in this exact order**:
    1. All meta-information above (retweet info, tags, hyperlinks, and hashtags) should be replaced with a single space.
    2. Everything other than letters, numbers, and spaces should be replaced with a single space.
    3. All letters should be lowercase.
    4. All words should be separated by exactly one space, and leading/trailing whitespace should be removed (stripped).
    
The columns in the outputted DataFrame must be in the order `['text', 'num_hashtags', 'mc_hashtags', 'num_tags', 'num_links', 'is_retweet']`. (Remember, the DataFrame that `create_features` is called on only has a single column, `'text'`.)

***Notes:***
- It's a good idea to make helper function for each column.
- The `\w` character class in regex **does not** refer to letters, numbers, and spaces (or even just letters and numbers). As such, you can't use it here!
- `create_features` will take a while to run on the entire dataset ‚Äì test it on a small sample first!

In [211]:
# The doctests/public tests don't test your work on the `ira` data,
# but the hidden tests do.
# So, make sure to thoroughly test your work yourself!
fp = os.path.join('data', 'ira.csv')
ira = pd.read_csv(fp, names=['id', 'name', 'date', 'text'])

In [219]:
hashtag_list(ira['text'])

0        [Exercise, LoseBellyFat, CatTV, TeenWolf‚Ä¶]
1                                                []
2                                            [tech]
3                                            [news]
4           [IHatePokemonGoBecause, PokesAreJokes.]
                            ...
89995                                    [politics]
89996                         [ThingsYouCantIgnore]
89997                                            []
89998                                [rantfortoday]
89999                                        [news]
Name: text, Length: 90000, dtype: object

In [267]:
ira['text']

0        The Best Exercise To Lose Belly Fat In 2 weeks...
1        RT @Philanthropy: Dozens of ‚Äòhate groups‚Äô have...
2        Artificial intelligence can find, map poverty,...
3        Uber balks at rules proposed by world‚Äôs busies...
4        RT @dirtroaddiva1: #IHatePokemonGoBecause he  ...
                               ...
89995    Trump: Kasich shouldn't be allowed to run http...
89996    RT @JefLeeson: #ThingsYouCantIgnore The last s...
89997    RT @nealcarter: When someone said the first li...
89998    RT @indigenous01: #rantfortoday I speak the Wo...
89999    10 Things to Know for Monday https://t.co/XoOg...
Name: text, Length: 90000, dtype: object

In [258]:
'RTX '.replace(r'^(?:RT)+',"")

'RTX '

In [322]:
df = pd.DataFrame(columns=[['text', 'num_hashtags', 'mc_hashtags', 'num_tags', 'num_links', 'is_retweet']])
df['num_hashtags'] = hashtag_list(ira['text']).apply(lambda x : len(x))
df['mc_hashtags'] = most_common_hashtag(hashtag_list(ira['text']))

df['num_tags'] = ira['text'].apply(lambda x : len(re.findall(r'@\w+',x)))
df['is_retweet'] = ira['text'].apply(lambda x : x[0:2] == 'RT')
df['num_links'] = ira['text'].apply(lambda x: len(re.findall(r'(?:http:\/\/[^\s]+|https:\/\/[^\s]+)',x)))

clean_text = []
counter = 0
for n in ira['text'][:30]:
    cleaned = n.replace('RT',' ')
    tags = re.findall(r'@\w+',cleaned)
    for l in tags:
        cleaned = cleaned.replace(l,' ')
    hashes = hashtag_list(ira['text'])
    #print(hashes)
    for k in hashes[counter]:
        cleaned = re.sub(fr'(?:\s|\b)#{k}(?:\s|\b)',' ', cleaned)
    links = re.findall(r'(?:http:\/\/[^\s]+|https:\/\/[^\s]+)',cleaned)
    #print(cleaned)
    for b in links:
        cleaned = cleaned.replace(b,' ')
    filtered = re.findall(r'[^A-Za-z0-9 ]+',cleaned)
    for c in filtered:
        cleaned.replace(c,' ')
    cleaned = cleaned.lower()
    words = re.findall(r'\b([a-z0-9]+)\b', cleaned)
    clean_text.append(' '.join(words))
    counter+=1
df['text'] = pd.Series(clean_text)

In [328]:
df['text'].values[4]

array(['he didn t let me do that for a klondike bar screw you pokemon'],
      dtype=object)

In [286]:
testdata = [['RT @DSC80: Text-cleaning is cool! #NLP https://t.co/xsfdw88d #NLP1 #NLP1']]
test = pd.DataFrame(testdata, columns=['text'])
test.columns
#out = create_features(test)

Index(['text'], dtype='object')

In [315]:
testdata = [['RT @DSC80: Text-cleaning is cool! #NLP https://t.co/xsfdw88d #NLP1 #NLP1']]
test = pd.DataFrame(testdata, columns=['text'])
out = create_features(test)
anscols = ['text', 'num_hashtags', 'mc_hashtags', 'num_tags', 'num_links', 'is_retweet']
ansdata = [['text cleaning is cool', 3, 'NLP1', 1, 1, True]]
ans = pd.DataFrame(ansdata, columns=anscols)
(out == ans).all().all()

0    [NLP, NLP1, NLP1]
Name: text, dtype: object
NLP
NLP1
NLP1
 : Text-cleaning is cool! https://t.co/xsfdw88d

True

In [316]:
out

,text,num_hashtags,mc_hashtags,num_tags,num_links,is_retweet
0,text cleaning is cool,3,NLP1,1,1,True

In [317]:
ans

,text,num_hashtags,mc_hashtags,num_tags,num_links,is_retweet
0,text cleaning is cool,3,NLP1,1,1,True

In [270]:

df['text'].values[:30]

array([['the best to lose belly fat in 2 weeks'],
       ['dozens of hate groups have charity status chronicle study finds'],
       ['artificial intelligence can find map poverty researchers say'],
       ['uber balks at rules proposed by world s busiest airport'],
       ['he didn t let me do that for a klondike bar screw you pokemon'],
       ['chick fil a remains closed after violations'],
       ['we cannot afford to wait to address this public health crisis we must quickly fund efforts to stop zika s spread'],
       ['that the two leading republican candidates are an ignorant bully and an ignorant preacher'],
       ['rj ommio from nothing prod by davo'],
       ['hill street vida blues'],
       ['all you wanted to know about hillary'],
       ['photos man driving atv hit by semi truck while leading police on pursuit'],
       ['you don t have to use your daughters and wives as surrogates for your outrage over you can just be offende'],
       ['celebrity biographer wendy leigh dies in london at age 65'],
       ['48 citizens escape horrible acts of terrorists in eastern neighborhoods of aleppo'],
       ['its remaining divisions will be assigned to a state owned strategic conglomerate ukroboronprom'],
       ['video 2fic the mantle'],
       ['hillary s campaign manager deleted all his tweets after the fbi re opened the case they are spiralling down h'],
       ['nfl free agency 2016 live updates brandon browner released on day 2'],
       ['ohio voters request absentee ballots for presidential election at record pace'],
       ['i don t think i have either this was amazingly funny'],
       ['really facebook people kissing is bad out of all the things to take down they remove two loving people kissing'],
       ['obama wants us to believe those people are peaceful refugees after what has happened during'],
       ['back at one day at a time'],
       ['scprosecutor no reason to charge officer who body slammed student ht'],
       ['was considered not nice regarding paris amp comments months ago'],
       ['ap fact check some clinton email misstatements'],
       ['news post biden tamps down 2020 speculation four years is a lifetime in american politics'],
       ['denham springs man dies after crashing car into horse near satsuma horse also died'],
       ['try and whatever color']], dtype=object)

In [318]:
# don't change this cell, but do run it -- it is needed for the tests
# (yes, we know it says "hidden" ‚Äì there are still truly hidden tests in this question)
fp_hidden = 'data/ira_test.csv'
ira_hidden = pd.read_csv(fp_hidden, header=None)
text_hidden = ira_hidden.iloc[:, -1:]
text_hidden.columns = ['text']

test_hidden = create_features(text_hidden)

In [319]:
grader.check("q5")

q5 results: All test cases passed!

## Congratulations! You're done! üèÅ

Submit your `lab.py` file to Gradescope. Note that you only need to submit the `lab.py` file; this notebook should not be uploaded.

Before submitting, you should ensure that all of your work is in the `lab.py` file. You can do this by running the doctests below, which will verify that your work passes the public tests **and** that your work is in the `lab.py` file. Run the cell below; you should see no output.

In [320]:
!python -m doctest lab.py

<doctest lab.relevant_word[1]>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  reviews_ser = pd.read_csv(fp, header=None, squeeze=True)
<doctest lab.tfidf_data[1]>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  reviews_ser = pd.read_csv(fp, header=None, squeeze=True)

In addition, `grader.check_all()` will verify that your work passes the public tests.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [321]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!